- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: present
    update_cache: true

- name: Delete old config
  file:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    state: absent

- name: Configure auto patching
  copy:
    src: 50-unattended-upgrades
    dest: /etc/apt/apt.conf.d/50-unattended-upgrades