- name: Install Java JRE 19
  apt:
    name: openjdk-19-jre-headless
    state: latest

- name: Create Minecraft server data directory
  file:
    path: /opt/minecraft/servers/vanilla
    state: directory
    recurse: yes
    mode: 0770
    owner: minecraft
    group: minecraft

- name: Check if Purpur is already installed
  stat:
    path: /opt/minecraft/servers/vanilla/purpur-server.jar
  register: purpur_installed

- name: Download Purpur
  get_url:
    url: https://api.purpurmc.org/v2/purpur/1.20.2/latest/download
    dest: /opt/minecraft/servers/vanilla/purpur-server.jar
    mode: 0770
    owner: minecraft
    group: minecraft
  when: not purpur_installed.stat.exists

- name: Copy server.properties
  template:
    src: server.properties.j2
    dest: /opt/minecraft/servers/vanilla/server.properties
    mode: 0660
    owner: minecraft
    group: minecraft

- name: Accept EULA
  copy:
    dest: /opt/minecraft/servers/vanilla/eula.txt
    content: eula=true
    mode: 0660
    owner: minecraft
    group: minecraft

- name: Copy run-server.sh
  copy:
    src: run-server.sh
    dest: /opt/minecraft/servers/vanilla/run-server.sh
    mode: 0770
    owner: minecraft
    group: minecraft

- name: Copy spigot.yml
  copy:
    src: spigot.yml
    dest: /opt/minecraft/spigot.yml
    mode: 0660
    owner: minecraft
    group: minecraft