- name: Install Zabbix repo
  copy:
    dest: /etc/apt/sources.list.d/zabbix.list
    content: |
      # Zabbix main repository
      deb https://repo.zabbix.com/zabbix/6.4/ubuntu jammy main
      deb-src https://repo.zabbix.com/zabbix/6.4/ubuntu jammy main

      # Zabbix unstable repository
      deb https://repo.zabbix.com/zabbix/6.3/ubuntu jammy main
      deb-src https://repo.zabbix.com/zabbix/6.3/ubuntu jammy main

- name: apt update
  apt:
    update_cache: yes

- name: Install Zabbix Agent 2
  apt:
    name: zabbix-agent2
    state: latest

- name: Configure Zabbix Agent 2
  template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: zabbix
    group: zabbix
    mode: 0660

- name: Configure Zabbix Agent 2 PSK
  copy:
    src: zabbix-agent-psk
    dest: /etc/zabbix/zabbix-agent-psk
    decrypt: yes
    owner: zabbix
    group: zabbix
    mode: 0660

- name: Add Zabbix user to Docker group
  user:
    name: zabbix
    groups: docker
  ignore_errors: true

- name: Add Zabbix account to Minecraft group
  user:
    name: zabbix
    groups:
      - minecraft

- name: Restart and enable Zabbix Agent 2 service
  systemd:
    name: zabbix-agent2
    state: restarted
    enabled: yes