- name: Get a list of all installed packages
  package_facts:
    manager: auto

- name: Download zabbix-release package
  get_url:
    url: https://repo.zabbix.com/zabbix/6.4/ubuntu-arm64/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb
    dest: /tmp/zabbix-release_6.4-1+ubuntu22.04_all.deb
  when: "'zabbix-agent2' not in ansible_facts.packages"

- name: Install zabbix-release package
  apt:
    deb: /tmp/zabbix-release_6.4-1+ubuntu22.04_all.deb
  when: "'zabbix-agent2' not in ansible_facts.packages"

- name: Update apt cache and install zabbix-agent2
  apt:
    update_cache: yes
    name: zabbix-agent2
    state: latest
  when: "'zabbix-agent2' not in ansible_facts.packages"

- name: Configure Zabbix Agent 2
  template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: zabbix
    group: zabbix
    mode: 0660

- name: Configure Zabbix Agent 2 PSK
  copy:
    src: zabbix-agent-psk
    dest: /etc/zabbix/zabbix-agent-psk
    decrypt: yes
    owner: zabbix
    group: zabbix
    mode: 0660

- name: Add Zabbix user to Docker group
  user:
    name: zabbix
    groups: docker
  ignore_errors: true

- name: Add Zabbix account to Minecraft group
  user:
    name: zabbix
    groups:
      - minecraft

- name: Restart and enable Zabbix Agent 2 service
  systemd:
    name: zabbix-agent2
    state: restarted
    enabled: yes