- name: Ensure gpg is installed
  apt:
    name: gpg
    state: latest

# https://www.jeffgeerling.com/blog/2022/aptkey-deprecated-debianubuntu-how-fix-ansible
- name: Add Zabbix apt repo key
  ansible.builtin.get_url:
    url: https://repo.zabbix.com/zabbix-official-repo.key
    dest: /etc/apt/trusted.gpg.d/zabbix-official-repo.asc
    mode: '0644'

- name: Add Zabbix apt repo
  ansible.builtin.apt_repository:
    repo: "deb https://repo.zabbix.com/zabbix/{{ zabbix_version }}/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} main"
    state: present

- name: apt update
  apt:
    update_cache: yes

- name: Install Zabbix Agent 2
  apt:
    name: zabbix-agent2
    state: latest
  notify: Restart and enable Zabbix Agent 2 service

- name: Configure Zabbix Agent 2
  template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: zabbix
    group: zabbix
    mode: 0660
  notify: Restart and enable Zabbix Agent 2 service

- name: Add Zabbix user to Docker group
  user:
    name: zabbix
    groups: docker
  ignore_errors: true