- name: Add Kopia repo key
  apt_key:
    url: https://kopia.io/signing-key

- name: Add Kopia repo
  apt_repository:
    repo: "deb http://packages.kopia.io/apt/ stable main"

- name: Install Kopia
  apt:
    name: kopia
    state: latest

- name: Check if Kopia is already configured
  stat:
    path: /opt/minecraft/backups/kopia/kopia.repository.f
  register: kopia_configured

- name: Create kopia local filesystem repository
  shell: kopia repository create filesystem --path /opt/minecraft/backups/kopia -p={{ kopia_password }}
  when: not kopia_configured.stat.exists

- name: Configure Kopia snapshot retention policy
  shell: |
      kopia policy set --global --keep-hourly 24
      kopia policy set --global --keep-daily 7
      kopia policy set --global --keep-weekly 4
      kopia policy set --global --keep-monthly 12
      kopia policy set --global --keep-annual 3
      kopia policy set --global --keep-latest 0