- name: Add Kopia repo key
  apt_key:
    url: https://kopia.io/signing-key

- name: Add Kopia repo
  apt_repository:
    repo: "deb http://packages.kopia.io/apt/ stable main"

- name: Install Kopia
  apt:
    name: kopia
    state: latest

- name: Check if Kopia is already configured
  stat:
    path: /opt/minecraft/backups/kopia/kopia.repository.f
  register: kopia_configured

- name: Create Kopia repository
  shell: kopia repository create b2 -p={{ kopia_password }} --bucket={{ kopia_b2_bucket_name }} --key-id={{ kopia_b2_bucket_key_id }} --key={{ kopia_b2_bucket_key }}
  when: not kopia_configured.stat.exists

- name: Connect to Kopia repository
  shell: kopia repository connect b2 -p={{ kopia_password }} --bucket={{ kopia_b2_bucket_name }} --key-id={{ kopia_b2_bucket_key_id }} --key={{ kopia_b2_bucket_key }}
  when: not kopia_configured.stat.exists

- name: Configure Kopia snapshot retention policy
  shell: |
      kopia policy set --global --keep-hourly 24
      kopia policy set --global --keep-daily 7
      kopia policy set --global --keep-weekly 4
      kopia policy set --global --keep-monthly 12
      kopia policy set --global --keep-annual 3
      kopia policy set --global --keep-latest 0
  when: not kopia_configured.stat.exists