- name: Install cron
  apt:
    name: cron
    state: latest

- name: Create hourly cron backup job
  cron:
    name: Minecraft server backup every hour
    job: /opt/minecraft/backups/scripts/backup-server.sh
    minute: "0"